;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Evidence.Objective.Document",DevComment="")
+GameplayTagList=(Tag="Evidence.Objective.Test",DevComment="")
+GameplayTagList=(Tag="Evidence.Trail.Tobacco",DevComment="")
+GameplayTagList=(Tag="Icons.Playstation",DevComment="")
+GameplayTagList=(Tag="Icons.Xbox",DevComment="")
+GameplayTagList=(Tag="KeyGroup.Gamepad",DevComment="")
+GameplayTagList=(Tag="KeyGroup.KeyboardMouse",DevComment="")
+GameplayTagList=(Tag="MappingPreset.Alternate",DevComment="")
+GameplayTagList=(Tag="MappingPreset.Default",DevComment="")
+GameplayTagList=(Tag="Status.PlayerInSight",DevComment="")
+GameplayTagList=(Tag="Status.Stunned",DevComment="")

